define(

	function () {

		"use strict";

		return {
		
			ROUTE_CHANGE			:	"ROUTE_CHANGE",

			VIEW_INITIALIZED		:	"VIEW_INITIALIZED",
			VIEW_UPDATED			:	"VIEW_UPDATED",

			VIEW_LOAD_STARTED		:	"VIEW_LOAD_STARTED",
			VIEW_LOAD_COMPLETED		:	"VIEW_LOAD_COMPLETED",

			VIEW_IN_STARTED			:	"VIEW_IN_STARTED",
			VIEW_IN_COMPLETED		:	"VIEW_IN_COMPLETED",

			VIEW_OUT_STARTED		:	"VIEW_OUT_STARTED",
			VIEW_OUT_COMPLETED		:	"VIEW_OUT_COMPLETED",

			VIEW_CHANGE_STARTED		:	"VIEW_CHANGE_STARTED",
			VIEW_CHANGE_COMPLETED	:	"VIEW_CHANGE_COMPLETED",

			VIEW_DESTROYED			:	"VIEW_DESTROYED",

			UPDATE_TITLE			:	"UPDATE_TITLE",
			CLOSE_VIEW_GROUP		:	"CLOSE_VIEW_GROUP"
		};
	}
);